blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Feature Request
    url: https://github.com/mcchrish/nnn.vim/discussions/new?category=ideas
    about: Share ideas for new features
  - name: â“ Ask a Question
    url: https://github.com/mcchrish/nnn.vim/discussions/new?category=q-a
    about: Ask the community for help
